version: 2.1

variables:
    todo-vm-deploy: true
    hogehoge: hoge
 
orbs:
    hello: circleci/hello-build@0.0.7 # circleci/buildpack-deps Docker イメージを使います

jobs:
    variables:
        todo-vm-deploy: true
        hogehoge: hoge
    
    build:
        docker: 
            - image: ubuntu:14.04
        steps:
            - run: echo << varibales.hogehoge >>
    # - when:
    #     condition: << variables.todo-vm-deploy >>
    #     steps:
    #       - hello/hello-build:
    #         - to: "vm-deploy"
