version: 2.1

# environment:
#     todo-vm-deploy: true
#     hogehoge: hoge
parameters: # Pipelineパラメータ
  parametersDirectoryPath:
    type: string
    default: "Azure/parameters"

jobs:
  contexttest:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - run: echo ${ENV1}
      - run: echo ${ENV2}

  looptest:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - checkout
      - run:
          name: "ls paramdir"
          command: |
            echo 
            while read paramfile; do  echo $paramfile ; done < <(ls -A -1 << pipeline.parameters.parametersDirectoryPath >> )


workflows:
  MSP-Workflow:
    jobs:
      - looptest
      # - contexttest:
      #     context: 
      #       Context1
      #       Context2


# orbs:
#     hello: circleci/hello-build@0.0.7 # circleci/buildpack-deps Docker イメージを使います


# jobs:
#     build:
#         environment:
#             todo-vm-deploy: true
#             hogehoge: hoge
        
#         docker: 
#             - image: ubuntu:14.04
#         steps:
#             - run: echo << .Environment.hogehoge >>
    # - when:
    #     condition: << variables.todo-vm-deploy >>
    #     steps:
    #       - hello/hello-build:
    #         - to: "vm-deploy"
