version: 2.1

# environment:
#     todo-vm-deploy: true
#     hogehoge: hoge
 
orbs:
    hello: circleci/hello-build@0.0.7 # circleci/buildpack-deps Docker イメージを使います

workflows:
    MSP-Workflow:
        jobs:
            - hello/hello-build

# jobs:
#     build:
#         environment:
#             todo-vm-deploy: true
#             hogehoge: hoge
        
#         docker: 
#             - image: ubuntu:14.04
#         steps:
#             - run: echo << .Environment.hogehoge >>
    # - when:
    #     condition: << variables.todo-vm-deploy >>
    #     steps:
    #       - hello/hello-build:
    #         - to: "vm-deploy"
