version: 2.1

variables:
    todo-vm-deploy: true
 
orbs:
    hello: circleci/hello-build@0.0.7 # circleci/buildpack-deps Docker イメージを使います

workflows:
    "MSP Workflow":
        jobs:
            - when:
                condition: << variables.todo-vm-deploy >>
                steps:
                  - hello/hello-build
