version: 2.1

# environment:
#     todo-vm-deploy: true
#     hogehoge: hoge

jobs:
  contexttest:
    docker:
      - image: "circleci/node:9.6.1"
    steps:
      - run: echo ${ENV1}
      - run: echo ${ENV2}


workflows:
  MSP-Workflow:
    jobs:
      - contexttest:
          context: 
            Context1
            Context2


# orbs:
#     hello: circleci/hello-build@0.0.7 # circleci/buildpack-deps Docker イメージを使います


# jobs:
#     build:
#         environment:
#             todo-vm-deploy: true
#             hogehoge: hoge
        
#         docker: 
#             - image: ubuntu:14.04
#         steps:
#             - run: echo << .Environment.hogehoge >>
    # - when:
    #     condition: << variables.todo-vm-deploy >>
    #     steps:
    #       - hello/hello-build:
    #         - to: "vm-deploy"
